# This settings for local only, Do not use production it!!!
version: '3'
services:
    minio:
        image: 'minio/minio:RELEASE.2020-09-05T07-14-49Z'
        ports:
            - 9000:9000
        environment:  # FIXME!!!
            - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
            - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        command: ['server', '/data']
        # TODO volumes settings

    mongo:
        image: 'mongo:4.4.0-bionic'
        ports:
            - 27017:27017
        # environment:  # FIXME!!!
        #     - MONGO_INITDB_ROOT_USERNAME=root
        #     - MONGO_INITDB_ROOT_PASSWORD=example
        # TODO volumes settings

    client_nginx:
       image: 'nginx:1.19.2-alpine'
       ports:
           - 8080:80
       volumes:
           - $PWD/packages/client/dist:/usr/share/nginx/html:ro
